services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    networks:
      default:
        external: true
        name: manicel
